[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

# Proxy da API para a Function (sem CORS no navegador)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
