[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbyh3YoV7WOCcC80KLTuaCQsXM-JrP9UryY2FTjVXuFMgdicjB-FrPzeKWsH5-c0tMWX/exec"
  status = 200
  force = true

# SPA fallback (manter)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
